version: '3.8'

services:
  database:
    image: postgres:16
    container_name: users-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - users-network

  rooms-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/users_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    networks:
      - users-network

volumes:
  db_data:

networks:
  users-network:
    driver: bridge
